version: "3"
services:

 nginx:
  image: nginx:alpine
  container_name: thinkcmfweb
  ports:
    - "80:80"
  links:
    - php-fpm
  volumes:
    - ./www/:/var/www/html/:rw
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf/default.conf:/etc/conf/default.conf:ro
 php-fpm:
  build: ./php-fpm
  container_name: thinkcmfphp
  ports:
    - "9000:9000"
  volumes:
    - ./www/:/var/www/html/:rw
    - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
  links:
    - mysql
  privileged: true 
 mysql:
  image: mysql:5.7 
  ports:
    - "3306:3306"
  container_name: thinkcmfdb
  volumes:
    - ./mysql/data/:/var/lib/mysql/
  environment:
    - MYSQL_ROOT_PASSWORD=thinkcmf
    - MYSQL_USER=thinkcmf
    - MYSQL_PASSWORD=thinkcmf
